### ISSUE TITLE
Sign up issue.

### ISSUE THREAD

**Issue by Trhover** [CyberCat3/website#1]
When you sign up, you don't go into the account.
That means you think it's runnning slow and click again.
When you click again you see the text "Account aleready exists" which in itself isn't that pretty. (ACCOUNT_ALEREADY_EXISTS)
Creating the illusion that every single username is aleready taken.

**Comment by CyberCat3** [comment]
Thanks, I'll look into it!

**Comment by CyberCat3** [comment]
Should be fixed in newest commit.
