### ISSUE TITLE
LOGIN STUPID

### ISSUE THREAD

**Issue by Trhover** [CyberCat3/website#2]
DAS LOGIN STUPID IS.
IF USE GOOGLE FILL, YOU HAV TO KLIKK BUTTON FOR IT TO ACTUALLY DETECT, AND YOU CAN'T PRESS SIGN IN YET.

**Comment by Trhover** [comment]
# ØV, DAS NOT `ASNWERED` HAS BEEN.

**Comment by CyberCat3** [comment]
I'll take a look at it, chill.

**Comment by Trhover** [comment]
OK I CHILL AM

**Comment by CyberCat3** [comment]
This should have been fixed in the newest commit.

**Comment by Trhover** [comment]
REOPEN. IT FIXED HAS NOT BEEN.

**Comment by Trhover** [comment]
> ´This should have been fixed in the newest commit.´
NO
