### ISSUE TITLE
Text out of the screen.

### ISSUE THREAD

**Issue by Trhover** [CyberCat3/website#8]
If you write too much text, the messege goes out of the screen and the program 
![image](https://user-images.githubusercontent.com/60517873/73591308-54de1580-44ed-11ea-81c0-a2a54a931459.png)

Also the place, thingy where you type text goes **with** the messege.
All the messeges get moved to the right.

You could make the messege add a new line downwards when the limits are reached.

**Comment by Trhover** [comment]
It's not a  bug

**Comment by Trhover** [comment]
It's a bot.

**Comment by CyberCat3** [comment]
# This is now fixed!
