### ISSUE TITLE
Emoji system

### ISSUE THREAD

**Issue by Trhover** [CyberCat3/website#9]
What it says.

**Comment by CyberCat3** [comment]
Hold Windows tasten inde, og tryk på punktum.😊😊😊
Det virker faktisk overalt! Også i Notepad!
![image](https://user-images.githubusercontent.com/53492014/73744152-7c80e800-4750-11ea-8b9c-6c9a95ca89b7.png)

**Comment by Trhover** [comment]
Oh. I understand. 👍
